[MAIN]
VersionNUMBER=1.4

[IniFILES]
OS=OS.ini
IMAGE=Image.ini
DEFAULTTOOLBOXES="Basic Toolbox,ChassisPatches,Custom Toolbox,Option Toolbox,Prep Toolbox"
SITE="Zeppelin.ini,Site.ini,GlobalSite.ini,Win11.ini"
SITESELECTED=TRUE,TRUE,TRUE,TRUE,TRUE,TRUE

[Optional]
SerialEnabled=FALSE
IdentifierEnabled=FALSE
Identifier="N/A"
CostCenterEnabled=FALSE
CostCenter="Optional"

[FolderLOCATIONS]
PDDDIR=\\USDBTLBCA1MSH20\pdd$\PDDv2
IniFilesDIR=\\USDBTLBCA1MSH20\pdd$\IniFiles
LogDIR=\\USDBTLBCA1MSH20\pdd$\LogFiles
ConfigDIR=\\USDBTLBCA1MSH20\pdd$\Config
UtilDIR=\\USDBTLBCA1MSH20\pdd$\Utils
ProfileDIR=\\USDBTLBCA1MSH20\pdd$\IniFiles\Win11

WinPEDIR= 		\\USDBTLBCA1MSH20\pdd$\WinPE
ImageDIR= 		\\USDBTLBCA1MSH20\Images$
I386DIR= 		\\USDBTLBCA1MSH20\pdd$\OS

BasicTOOLBOX = 		\\USDBTLBCA1MSH20\Toolbox$\Basic_Toolbox
ChassisPatchesTOOLBOX = \\USDBTLBCA1MSH20\Toolbox$\Chassis_Patches
CustomTOOLBOX = 	\\USDBTLBCA1MSH20\Toolbox$\Custom_Toolbox
LanguageTOOLBOX = 	\\USDBTLBCA1MSH20\Toolbox$\Language_Toolbox
OptionTOOLBOX = 	\\USDBTLBCA1MSH20\Toolbox$\Option_Toolbox
PrepTOOLBOX = 		\\USDBTLBCA1MSH20\Toolbox$\Prep_Toolbox
SiteTOOLBOX = 		\\USDBTLBCA1MSH20\Toolbox$\Site_Toolbox
GlobalSiteTOOLBOX =	\\USDBTLBCA1MSH20\Toolbox$\Global_Site_Toolbox
ZeppelinTOOLBOX = 	\\USDBTLBCA1MSH20\Toolbox$\Zeppelin_Toolbox

[PDD]
RoleIDENTIFIER="YY,NB,DT,LT,QQ,PW,PY,VH,VW,WS,X1,XX,XP,XT,TC,FD,FN,FW,MS,DH"
OuPREFIX="DXC-RIVER2,USDBTLBCA1,USDFLDSSR1"
DOMAIN="CODE1.EMI.PHILIPS.COM"
InstallerEnabled=TRUE
InstallerACC=code1\

InstallMachinePART=TRUE
InstallUserPART=TRUE
VerifySelections=TRUE

PartCHOEnabled=FALSE
PartCHO=0
PartSize=0

UpdateBIOS=FALSE
UpdateBIOSOption=FALSE
DisableUAC=TRUE
UserByDefaultAdmin=TRUE

[Keyboard]
LayoutEnabled=TRUE
LayoutExtra=
LayoutDefault=

[OperatingSYSTEM]
6.4 = WIN11
6.3 = WIN10
; 6.1 = WIN7
; 6.0 = VISTA
; 5.1 = WXP
