[MAIN]
VersionNUMBER=1.4

[IniFILES]
OS=OS.ini
IMAGE=Image.ini
DEFAULTTOOLBOXES="Basic Toolbox,ChassisPatches,Custom Toolbox,Option Toolbox,Prep Toolbox"
SITE="Zeppelin.ini,Site.ini,GlobalSite.ini,Win11.ini"
SITESELECTED=TRUE,TRUE,TRUE,TRUE,TRUE,TRUE

[Optional]
SerialEnabled=FALSE
IdentifierEnabled=FALSE
Identifier="N/A"
CostCenterEnabled=FALSE
CostCenter="Optional"

[FolderLOCATIONS]
PDDDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\PDDv2
IniFilesDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\IniFiles
LogDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\LogFiles
ConfigDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\Config
UtilDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\Utils
ProfileDIR=\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\IniFiles\Win11

WinPEDIR= 		\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\WinPE
ImageDIR= 		\\usdbtlbca1msh20.code1.emi.philips.com\Images$
I386DIR= 		\\usdbtlbca1msh20.code1.emi.philips.com\pdd$\OS

BasicTOOLBOX = 		\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Basic_Toolbox
ChassisPatchesTOOLBOX = \\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Chassis_Patches
CustomTOOLBOX = 	\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Custom_Toolbox
LanguageTOOLBOX = 	\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Language_Toolbox
OptionTOOLBOX = 	\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Option_Toolbox
PrepTOOLBOX = 		\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Prep_Toolbox
SiteTOOLBOX = 		\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Site_Toolbox
GlobalSiteTOOLBOX =	\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Global_Site_Toolbox
ZeppelinTOOLBOX = 	\\usdbtlbca1msh20.code1.emi.philips.com\Toolbox$\Zeppelin_Toolbox

[PDD]
InstallerEnabled=TRUE
InstallerACC=code1\

InstallMachinePART=TRUE
InstallUserPART=TRUE
VerifySelections=TRUE

PartCHOEnabled=FALSE
PartCHO=0
PartSize=0

UpdateBIOS=FALSE
UpdateBIOSOption=FALSE
DisableUAC=TRUE
UserByDefaultAdmin=TRUE

[Keyboard]
LayoutEnabled=TRUE
LayoutExtra=
LayoutDefault=

[OperatingSYSTEM]
6.4 = WIN11
6.3 = WIN10
; 6.1 = WIN7
; 6.0 = VISTA
; 5.1 = WXP
